### PRODUCER
### Criar produtor
POST http://localhost:3000/producer
Content-Type: application/json

{
  "cpfCnpj": "39053344705",
  "name": "larissa"
}

### Listar todos os produtores
GET http://localhost:3000/producer

### Consultar produtor
GET http://localhost:3000/producer/31a97570-a3e7-4ddb-8d26-0ec2954cd071

### Atualizar produtor
PATCH http://localhost:3000/producer/5d04195c-6241-4a17-a555-8194af0b01bb
Content-Type: application/json

{
  "cpfCnpj": "12345678000195",
  "name": "Arleilson Atualizada"
}

### Remover produtor
DELETE http://localhost:3000/producer/37efd8d9-9055-4fc9-a530-82c138b582a7


### PROPERTY
### Criar propriedade
POST http://localhost:3000/property
Content-Type: application/json

{
  "name": "Fazenda Santa Helena",
  "city": "Xapuri",
  "state": "AC",
  "totalArea": 100,
  "agriculturalArea": 60,
  "vegetationArea": 40,
  "producerId": "5d04195c-6241-4a17-a555-8194af0b01bb"
}

### Listar todas as propriedades
GET http://localhost:3000/property

### Consultar propriedade
GET http://localhost:3000/property/d6e9c951-5047-4e66-b2f4-187996df2163

### Atualizar propriedade
PATCH http://localhost:3000/property/d6e9c951-5047-4e66-b2f4-187996df2163
Content-Type: application/json

{
  "name": "Fazenda Nova Esperança",
  "totalArea": 120,
  "agriculturalArea": 70,
  "vegetationArea": 50
}

### Remover propriedade
DELETE http://localhost:3000/property/d6e9c951-5047-4e66-b2f4-187996df2163


### CROP
### Criar cultura
POST http://localhost:3000/crops
Content-Type: application/json

{
  "name": "Soja",
  "season": "2024/2025",
  "propertyId": "7dc52ca9-4466-4ee7-b041-62cb2211ab3b"
}

### Listar todas as culturas
GET http://localhost:3000/crops

### Consultar cultura por ID
GET http://localhost:3000/crops/7ba4bbc8-614e-4bfe-91ee-e5cc1c01b2ec

### Atualizar cultura
PATCH http://localhost:3000/crops/7ba4bbc8-614e-4bfe-91ee-e5cc1c01b2ec
Content-Type: application/json

{
  "name": "Milho",
  "season": "2025/2026"
}

### Remover cultura
DELETE http://localhost:3000/crops/7ba4bbc8-614e-4bfe-91ee-e5cc1c01b2ec
