### PRODUCER
### Criar produtor
POST http://localhost:3000/producer
Content-Type: application/json

{
  "cpfCnpj": "39053344705",
  "name": "larissa"
}

### Listar todos os produtores
GET http://localhost:3000/producer

### Consultar produtor
GET http://localhost:3000/producer/b551a8a0-a800-413b-bb56-0c0fae24f60b

### Atualizar produtor
PATCH http://localhost:3000/producer/b551a8a0-a800-413b-bb56-0c0fae24f60b
Content-Type: application/json

{
  "cpfCnpj": "12345678000195",
  "name": "Arleilson Atualizada"
}

### Remover produtor
DELETE http://localhost:3000/producer/b551a8a0-a800-413b-bb56-0c0fae24f60b


### PROPERTY
### Criar propriedade
POST http://localhost:3000/property
Content-Type: application/json

{
  "name": "Fazenda Santa Helena",
  "city": "Xapuri",
  "state": "AC",
  "totalArea": 100,
  "agriculturalArea": 60,
  "vegetationArea": 40,
  "producerId": "b551a8a0-a800-413b-bb56-0c0fae24f60b"
}

### Listar todas as propriedades
GET http://localhost:3000/property

### Consultar propriedade
GET http://localhost:3000/property/5a69a372-368f-4d9f-9316-72a21f56b37d

### Atualizar propriedade
PATCH http://localhost:3000/property/5a69a372-368f-4d9f-9316-72a21f56b37d
Content-Type: application/json

{
  "name": "Fazenda Nova Esperança",
  "totalArea": 120,
  "agriculturalArea": 70,
  "vegetationArea": 50
}

### Remover propriedade
DELETE http://localhost:3000/property/5a69a372-368f-4d9f-9316-72a21f56b37d


### CROP
### Criar cultura
POST http://localhost:3000/crops
Content-Type: application/json

{
  "name": "Soja",
  "season": "2024/2025",
  "propertyId": "5a69a372-368f-4d9f-9316-72a21f56b37d"
}

### Listar todas as culturas
GET http://localhost:3000/crops

### Consultar cultura por ID
GET http://localhost:3000/crops/184316b6-2486-40e6-a1d3-a230c42e1e10

### Atualizar cultura
PATCH http://localhost:3000/crops/184316b6-2486-40e6-a1d3-a230c42e1e10
Content-Type: application/json

{
  "name": "Milho",
  "season": "2025/2026"
}

### Remover cultura
DELETE http://localhost:3000/crops/184316b6-2486-40e6-a1d3-a230c42e1e10
